version: '2'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=22cd8c6f56c99e3f87d552f533c348ea1552bb0b
      - MYSQL_USER=play
      - MYSQL_PASSWORD=thisisatest
      - MYSQL_DATABASE=play

  web:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - redis
